### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by stelladraco27** [Willyfrog/silverbullet-backlinks#7]
After following the installation instructions, I can't seem to find any of the commands to actually use this plug. I can't tell if its me or a bug.

If you need more details from me please ask, I'll provide them.

**Comment by zefhemel** [comment]
You may want to use try this fork instead: https://github.com/silverbulletmd/silverbullet-backlinks

Very soon SB will have this functionality built in without the need for a separate plug.

**Comment by stelladraco27** [comment]
Thank you, I will check that link out.

**Comment by zefhemel** [comment]
In SB 0.5.0 the backlinks plug is built in, effectively (named linked mentions). When you upgrade make sure to uninstall the backlinks plug.
